[book]
title = "Основи програмування мовою Rust з AI-асистентом"
authors = ["Олексій Бичков"]
language = "uk"
multilingual = false
src = "src"

[build]
build-dir = "book"
create-missing = false

[output.html]
default-theme = "light"
preferred-dark-theme = "ayu"
additional-css = ["custom.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.search]
enable = true

[preprocessor.mermaid]
command = "mdbook-mermaid"
